name: flutter_easy_treeview
description: This widget visualises a tree structure, where a node can be any widget.
version: 0.5.0
homepage: https://github.com/kokohuang/flutter_easy_treeview

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
